<a href="https://colab.research.google.com/github/Amritha-Pradeep/Learn.Py/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [8]:
#please provide your answer below this line.
import numpy as np
a = np.random.rand(3,3)
print(a)

[[0.11823174 0.32544271 0.95075437]
 [0.7656063  0.42907283 0.91299627]
 [0.04141393 0.3377791  0.41253264]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [7]:
#please provide your answer below this line.
import numpy as np
a = np.arange(4,20).reshape(4,4)
print(a)
b = np.arange(7,23).reshape(4,4)
print(b)
a = np.arange(4,20).reshape(2,8)
b = np.arange(7,23).reshape(2,8)
x = np.vstack((a,b))
print(x)
y = np.hstack((a,b))
print(y)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[ 4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19]
 [ 7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22]]
[[ 4  5  6  7  8  9 10 11  7  8  9 10 11 12 13 14]
 [12 13 14 15 16 17 18 19 15 16 17 18 19 20 21 22]]
